const PDFDocument = require('pdfkit');

async function generatePDF(reportText, playerName) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Cover page
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#080810');

    doc.fontSize(32).fillColor('#7C6AF7').font('Helvetica-Bold')
      .text('Elo Arc', 60, 80);
    doc.fontSize(14).fillColor('#00E5A0')
      .text('Your chess. Evolved.', 60, 120);

    doc.moveTo(60, 150).lineTo(doc.page.width - 60, 150).strokeColor('#7C6AF7').lineWidth(2).stroke();

    doc.fontSize(22).fillColor('#EFEFEF').font('Helvetica-Bold')
      .text('Monthly Coaching Report', 60, 170);
    doc.fontSize(16).fillColor('#7A7A9A').font('Helvetica')
      .text(playerName, 60, 205);
    doc.fontSize(12).fillColor('#7A7A9A')
      .text(new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }), 60, 230);

    doc.addPage();
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#080810');

    // Content
    doc.fontSize(11).fillColor('#EFEFEF').font('Helvetica');

    const paragraphs = reportText.split('\n\n');
    let y = 60;

    for (const para of paragraphs) {
      if (para.startsWith('#')) {
        const level = para.match(/^#+/)[0].length;
        const text = para.replace(/^#+\s*/, '');
        const size = level === 1 ? 20 : level === 2 ? 16 : 13;
        const color = level === 1 ? '#7C6AF7' : level === 2 ? '#00E5A0' : '#EFEFEF';

        if (y > doc.page.height - 120) { doc.addPage(); doc.rect(0, 0, doc.page.width, doc.page.height).fill('#080810'); y = 60; }
        doc.fontSize(size).fillColor(color).font('Helvetica-Bold').text(text, 60, y, { width: doc.page.width - 120 });
        y += doc.heightOfString(text, { width: doc.page.width - 120, fontSize: size }) + 16;
      } else if (para.trim()) {
        const cleaned = para.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
        if (y > doc.page.height - 120) { doc.addPage(); doc.rect(0, 0, doc.page.width, doc.page.height).fill('#080810'); y = 60; }
        doc.fontSize(11).fillColor('#EFEFEF').font('Helvetica').text(cleaned, 60, y, { width: doc.page.width - 120 });
        y += doc.heightOfString(cleaned, { width: doc.page.width - 120, fontSize: 11 }) + 14;
      }
    }

    // Footer on last page
    doc.fontSize(9).fillColor('#7A7A9A')
      .text('Generated by Elo Arc AI • eloarc.com', 60, doc.page.height - 40, { align: 'center', width: doc.page.width - 120 });

    doc.end();
  });
}

module.exports = { generatePDF };
